Add linting to CI/CD
ScottLogic/openapi-forge-typescript pull request #16
Opened 2022-09-29 08:39 UTC by jhowlett-scottlogic

- use eslint for linting
- add two scripts to use eslint locally
- include a eslint workflow
- fix linting errors found

2022-10-10 14:12 UTC, jhowlett-scottlogic commented
address issue:PR for issue:https://github.com/ScottLogic/openapi-forge/issues/83

2022-10-10 15:35 UTC, Joe-Dunleavy commented on README.md
> +Two scripts are available to aid you find linting errors:
"aid you find" should be "help you find"

2022-10-10 15:37 UTC, jhowlett-scottlogic commented on README.md
> +Two scripts are available to aid you find linting errors:
thank you, will fix that now

2022-10-10 15:56 UTC, Joe-Dunleavy requested changes

2022-10-10 15:56 UTC, Joe-Dunleavy commented on README.md
> +This is also ran on a PR and push to main and will fail if any errors were found.
Did you mean "pushed to main"? minor issue but you've got two "and" in a row. "And" should only ever be used once in a sentence, unless making a list of things. Replace the second one with a full stop followed by "it will fail if any errors..."

2022-10-10 15:59 UTC, merged

2022-10-11 07:57 UTC, Joe-Dunleavy commented
LGTM