Include API metadata in output
ScottLogic/openapi-forge-typescript pull request #17
Opened 2022-09-29 12:44 UTC by osouthwell-scottlogic

Adds new handlebar file to include api metadata in output

2022-09-29 15:52 UTC, ColinEberhardt commented on template/info.ts.handlebars
> +export interface infoInterface {
Does this interface have to be generated? couldn't it be static, based on the OpenAPI spec?

2022-10-11 16:03 UTC, jhowlett-scottlogic approved these changes
You have addressed Colin's requested changes. Looks good to me

2022-10-12 13:19 UTC, jhowlett-scottlogic requested changes

2022-10-12 13:19 UTC, jhowlett-scottlogic commented on template/info.ts.handlebars
> +    name?: string;
info.licence.name is a required field

https://swagger.io/specification/#license-object

2022-10-12 13:52 UTC, jhowlett-scottlogic approved these changes
Looks good to me

2022-10-12 13:53 UTC, merged